(* ag32Lib - generated by L3 - Thu Nov 10 17:12:07 2022 *)
structure ag32Lib :> ag32Lib =
struct
open HolKernel boolLib bossLib
open utilsLib ag32Theory
val () = (numLib.prefer_num (); wordsLib.prefer_word ())
fun ag32_compset thms =
   utilsLib.theory_compset (thms, ag32Theory.inventory)
end